
backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "pagina_principal"
    label: "Landing Page"
    files:
      - label: "Conteúdo Principal"
        name: "conteudo"
        file: "content/landing-page.md"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Texto do Banner", name: "banner_text", widget: "string" }
          - { label: "Subtexto do Banner", name: "banner_subtext", widget: "string" }
          - { label: "Sobre Nós", name: "about", widget: "markdown" }
          - label: "Serviços"
            name: "services"
            widget: "list"
            fields:
              - { label: "Título", name: "title", widget: "string" }
              - { label: "Descrição", name: "description", widget: "string" }
              - { label: "Ícone", name: "icon", widget: "string", hint: "Nome do ícone do Font Awesome (ex: dumbbell, laptop, lock)" }
          - label: "Depoimentos"
            name: "testimonials"
            widget: "list"
            fields:
              - { label: "Nome do Cliente", name: "author", widget: "string" }
              - { label: "Profissão/Idade", name: "profession", widget: "string" }
              - { label: "Feedback", name: "feedback", widget: "text" }
          - label: "Informações de Contato"
            name: "contact_info"
            widget: "object"
            fields:
              - { label: "Endereço", name: "address", widget: "string" }
              - { label: "Telefone", name: "phone", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
